spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: brown
    password: brown

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true

  devtools:
    # Auto Restart
    restart:
      enabled: true
      additional-exclude: static/**,public/**
